// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: types/money/v1/money.proto

package v1

import (
	v1 "github.com/LexBokun/payment-service/pkg/api/enums/cryptocurrency/v1"
	v11 "github.com/LexBokun/payment-service/pkg/api/enums/fiatcurrency/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Универсальное представление денежек
type Money struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Amount      string                 `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`                              // Введённая сумма
	SuccessPaid string                 `protobuf:"bytes,2,opt,name=success_paid,json=successPaid,proto3" json:"success_paid,omitempty"` // Сумма + комиссия
	Fee         string                 `protobuf:"bytes,3,opt,name=fee,proto3" json:"fee,omitempty"`                                    // Комиссия (если есть)
	// Types that are valid to be assigned to Currency:
	//
	//	*Money_Crypto
	//	*Money_Fiat
	Currency      isMoney_Currency `protobuf_oneof:"currency"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_types_money_v1_money_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_types_money_v1_money_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_types_money_v1_money_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Money) GetSuccessPaid() string {
	if x != nil {
		return x.SuccessPaid
	}
	return ""
}

func (x *Money) GetFee() string {
	if x != nil {
		return x.Fee
	}
	return ""
}

func (x *Money) GetCurrency() isMoney_Currency {
	if x != nil {
		return x.Currency
	}
	return nil
}

func (x *Money) GetCrypto() v1.Currency {
	if x != nil {
		if x, ok := x.Currency.(*Money_Crypto); ok {
			return x.Crypto
		}
	}
	return v1.Currency(0)
}

func (x *Money) GetFiat() v11.Currency {
	if x != nil {
		if x, ok := x.Currency.(*Money_Fiat); ok {
			return x.Fiat
		}
	}
	return v11.Currency(0)
}

type isMoney_Currency interface {
	isMoney_Currency()
}

type Money_Crypto struct {
	Crypto v1.Currency `protobuf:"varint,4,opt,name=crypto,proto3,enum=enums.cryptocurrency.v1.Currency,oneof"` //BTC, TON ...
}

type Money_Fiat struct {
	Fiat v11.Currency `protobuf:"varint,5,opt,name=fiat,proto3,enum=enums.fiatcurrency.v1.Currency,oneof"` // RUB, ...
}

func (*Money_Crypto) isMoney_Currency() {}

func (*Money_Fiat) isMoney_Currency() {}

var File_types_money_v1_money_proto protoreflect.FileDescriptor

const file_types_money_v1_money_proto_rawDesc = "" +
	"\n" +
	"\x1atypes/money/v1/money.proto\x12\x0etypes.money.v1\x1a-enums/cryptocurrency/v1/crypto_currency.proto\x1a)enums/fiatcurrency/v1/fiat_currency.proto\"\xd4\x01\n" +
	"\x05Money\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\tR\x06amount\x12!\n" +
	"\fsuccess_paid\x18\x02 \x01(\tR\vsuccessPaid\x12\x10\n" +
	"\x03fee\x18\x03 \x01(\tR\x03fee\x12;\n" +
	"\x06crypto\x18\x04 \x01(\x0e2!.enums.cryptocurrency.v1.CurrencyH\x00R\x06crypto\x125\n" +
	"\x04fiat\x18\x05 \x01(\x0e2\x1f.enums.fiatcurrency.v1.CurrencyH\x00R\x04fiatB\n" +
	"\n" +
	"\bcurrencyB<Z:github.com/LexBokun/payment-service/pkg/api/types/money/v1b\x06proto3"

var (
	file_types_money_v1_money_proto_rawDescOnce sync.Once
	file_types_money_v1_money_proto_rawDescData []byte
)

func file_types_money_v1_money_proto_rawDescGZIP() []byte {
	file_types_money_v1_money_proto_rawDescOnce.Do(func() {
		file_types_money_v1_money_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_money_v1_money_proto_rawDesc), len(file_types_money_v1_money_proto_rawDesc)))
	})
	return file_types_money_v1_money_proto_rawDescData
}

var file_types_money_v1_money_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_types_money_v1_money_proto_goTypes = []any{
	(*Money)(nil),     // 0: types.money.v1.Money
	(v1.Currency)(0),  // 1: enums.cryptocurrency.v1.Currency
	(v11.Currency)(0), // 2: enums.fiatcurrency.v1.Currency
}
var file_types_money_v1_money_proto_depIdxs = []int32{
	1, // 0: types.money.v1.Money.crypto:type_name -> enums.cryptocurrency.v1.Currency
	2, // 1: types.money.v1.Money.fiat:type_name -> enums.fiatcurrency.v1.Currency
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_types_money_v1_money_proto_init() }
func file_types_money_v1_money_proto_init() {
	if File_types_money_v1_money_proto != nil {
		return
	}
	file_types_money_v1_money_proto_msgTypes[0].OneofWrappers = []any{
		(*Money_Crypto)(nil),
		(*Money_Fiat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_money_v1_money_proto_rawDesc), len(file_types_money_v1_money_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_money_v1_money_proto_goTypes,
		DependencyIndexes: file_types_money_v1_money_proto_depIdxs,
		MessageInfos:      file_types_money_v1_money_proto_msgTypes,
	}.Build()
	File_types_money_v1_money_proto = out.File
	file_types_money_v1_money_proto_goTypes = nil
	file_types_money_v1_money_proto_depIdxs = nil
}
