// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: enums/paymentmethod/v1/payment_method.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Методы оплаты (Юmoney, карта, ...)
type Method int32

const (
	Method_METHOD_PAYMENT_UNSPECIFIED Method = 0 // По умолчанию (не указано)
	Method_METHOD_YOOMONEY_WALLET     Method = 1 // Кошелек ЮMoney (PC)
	Method_METHOD_BANK_CARD           Method = 2 // Банковская карта (AC)
)

// Enum value maps for Method.
var (
	Method_name = map[int32]string{
		0: "METHOD_PAYMENT_UNSPECIFIED",
		1: "METHOD_YOOMONEY_WALLET",
		2: "METHOD_BANK_CARD",
	}
	Method_value = map[string]int32{
		"METHOD_PAYMENT_UNSPECIFIED": 0,
		"METHOD_YOOMONEY_WALLET":     1,
		"METHOD_BANK_CARD":           2,
	}
)

func (x Method) Enum() *Method {
	p := new(Method)
	*p = x
	return p
}

func (x Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Method) Descriptor() protoreflect.EnumDescriptor {
	return file_enums_paymentmethod_v1_payment_method_proto_enumTypes[0].Descriptor()
}

func (Method) Type() protoreflect.EnumType {
	return &file_enums_paymentmethod_v1_payment_method_proto_enumTypes[0]
}

func (x Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Method.Descriptor instead.
func (Method) EnumDescriptor() ([]byte, []int) {
	return file_enums_paymentmethod_v1_payment_method_proto_rawDescGZIP(), []int{0}
}

var File_enums_paymentmethod_v1_payment_method_proto protoreflect.FileDescriptor

const file_enums_paymentmethod_v1_payment_method_proto_rawDesc = "" +
	"\n" +
	"+enums/paymentmethod/v1/payment_method.proto\x12\x16enums.paymentmethod.v1*Z\n" +
	"\x06Method\x12\x1e\n" +
	"\x1aMETHOD_PAYMENT_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16METHOD_YOOMONEY_WALLET\x10\x01\x12\x14\n" +
	"\x10METHOD_BANK_CARD\x10\x02BDZBgithub.com/LexBokun/payment-service/pkg/api/enums/paymentmethod/v1b\x06proto3"

var (
	file_enums_paymentmethod_v1_payment_method_proto_rawDescOnce sync.Once
	file_enums_paymentmethod_v1_payment_method_proto_rawDescData []byte
)

func file_enums_paymentmethod_v1_payment_method_proto_rawDescGZIP() []byte {
	file_enums_paymentmethod_v1_payment_method_proto_rawDescOnce.Do(func() {
		file_enums_paymentmethod_v1_payment_method_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enums_paymentmethod_v1_payment_method_proto_rawDesc), len(file_enums_paymentmethod_v1_payment_method_proto_rawDesc)))
	})
	return file_enums_paymentmethod_v1_payment_method_proto_rawDescData
}

var file_enums_paymentmethod_v1_payment_method_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_enums_paymentmethod_v1_payment_method_proto_goTypes = []any{
	(Method)(0), // 0: enums.paymentmethod.v1.Method
}
var file_enums_paymentmethod_v1_payment_method_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enums_paymentmethod_v1_payment_method_proto_init() }
func file_enums_paymentmethod_v1_payment_method_proto_init() {
	if File_enums_paymentmethod_v1_payment_method_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enums_paymentmethod_v1_payment_method_proto_rawDesc), len(file_enums_paymentmethod_v1_payment_method_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enums_paymentmethod_v1_payment_method_proto_goTypes,
		DependencyIndexes: file_enums_paymentmethod_v1_payment_method_proto_depIdxs,
		EnumInfos:         file_enums_paymentmethod_v1_payment_method_proto_enumTypes,
	}.Build()
	File_enums_paymentmethod_v1_payment_method_proto = out.File
	file_enums_paymentmethod_v1_payment_method_proto_goTypes = nil
	file_enums_paymentmethod_v1_payment_method_proto_depIdxs = nil
}
