// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: payment/models/transaction/v1/operation.proto

package v1

import (
	v1 "github.com/LexBokun/payment-service/pkg/api/types/money/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Операция списания или зачисления
type Operation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"` // Реквизит: номер карты или адрес крипто-кошелька
	Money         *v1.Money              `protobuf:"bytes,3,opt,name=money,proto3" json:"money,omitempty"`     // Данные о сумме операции(amount, success_paid, fee)
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_payment_models_transaction_v1_operation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_payment_models_transaction_v1_operation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_payment_models_transaction_v1_operation_proto_rawDescGZIP(), []int{0}
}

func (x *Operation) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *Operation) GetMoney() *v1.Money {
	if x != nil {
		return x.Money
	}
	return nil
}

func (x *Operation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Operation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_payment_models_transaction_v1_operation_proto protoreflect.FileDescriptor

const file_payment_models_transaction_v1_operation_proto_rawDesc = "" +
	"\n" +
	"-payment/models/transaction/v1/operation.proto\x12\x1dpayment.models.transaction.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1atypes/money/v1/money.proto\"\xc8\x01\n" +
	"\tOperation\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12+\n" +
	"\x05money\x18\x03 \x01(\v2\x15.types.money.v1.MoneyR\x05money\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtBKZIgithub.com/LexBokun/payment-service/pkg/api/payment/models/transaction/v1b\x06proto3"

var (
	file_payment_models_transaction_v1_operation_proto_rawDescOnce sync.Once
	file_payment_models_transaction_v1_operation_proto_rawDescData []byte
)

func file_payment_models_transaction_v1_operation_proto_rawDescGZIP() []byte {
	file_payment_models_transaction_v1_operation_proto_rawDescOnce.Do(func() {
		file_payment_models_transaction_v1_operation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_models_transaction_v1_operation_proto_rawDesc), len(file_payment_models_transaction_v1_operation_proto_rawDesc)))
	})
	return file_payment_models_transaction_v1_operation_proto_rawDescData
}

var file_payment_models_transaction_v1_operation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_payment_models_transaction_v1_operation_proto_goTypes = []any{
	(*Operation)(nil),             // 0: payment.models.transaction.v1.Operation
	(*v1.Money)(nil),              // 1: types.money.v1.Money
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_payment_models_transaction_v1_operation_proto_depIdxs = []int32{
	1, // 0: payment.models.transaction.v1.Operation.money:type_name -> types.money.v1.Money
	2, // 1: payment.models.transaction.v1.Operation.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: payment.models.transaction.v1.Operation.updated_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_payment_models_transaction_v1_operation_proto_init() }
func file_payment_models_transaction_v1_operation_proto_init() {
	if File_payment_models_transaction_v1_operation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_models_transaction_v1_operation_proto_rawDesc), len(file_payment_models_transaction_v1_operation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payment_models_transaction_v1_operation_proto_goTypes,
		DependencyIndexes: file_payment_models_transaction_v1_operation_proto_depIdxs,
		MessageInfos:      file_payment_models_transaction_v1_operation_proto_msgTypes,
	}.Build()
	File_payment_models_transaction_v1_operation_proto = out.File
	file_payment_models_transaction_v1_operation_proto_goTypes = nil
	file_payment_models_transaction_v1_operation_proto_depIdxs = nil
}
