// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: enums/transactiontype/v1/transaction_type.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Тип перевода(INVOICE, WITHDRAW)
type Type int32

const (
	Type_TYPE_UNSPECIFIED Type = 0
	Type_TYPE_INVOICE     Type = 1
	Type_TYPE_WITHDRAW    Type = 2
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_INVOICE",
		2: "TYPE_WITHDRAW",
	}
	Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_INVOICE":     1,
		"TYPE_WITHDRAW":    2,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_enums_transactiontype_v1_transaction_type_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_enums_transactiontype_v1_transaction_type_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_enums_transactiontype_v1_transaction_type_proto_rawDescGZIP(), []int{0}
}

var File_enums_transactiontype_v1_transaction_type_proto protoreflect.FileDescriptor

const file_enums_transactiontype_v1_transaction_type_proto_rawDesc = "" +
	"\n" +
	"/enums/transactiontype/v1/transaction_type.proto\x12\x18enums.transactiontype.v1*A\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fTYPE_INVOICE\x10\x01\x12\x11\n" +
	"\rTYPE_WITHDRAW\x10\x02BFZDgithub.com/LexBokun/payment-service/pkg/api/enums/transactiontype/v1b\x06proto3"

var (
	file_enums_transactiontype_v1_transaction_type_proto_rawDescOnce sync.Once
	file_enums_transactiontype_v1_transaction_type_proto_rawDescData []byte
)

func file_enums_transactiontype_v1_transaction_type_proto_rawDescGZIP() []byte {
	file_enums_transactiontype_v1_transaction_type_proto_rawDescOnce.Do(func() {
		file_enums_transactiontype_v1_transaction_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enums_transactiontype_v1_transaction_type_proto_rawDesc), len(file_enums_transactiontype_v1_transaction_type_proto_rawDesc)))
	})
	return file_enums_transactiontype_v1_transaction_type_proto_rawDescData
}

var file_enums_transactiontype_v1_transaction_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_enums_transactiontype_v1_transaction_type_proto_goTypes = []any{
	(Type)(0), // 0: enums.transactiontype.v1.Type
}
var file_enums_transactiontype_v1_transaction_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enums_transactiontype_v1_transaction_type_proto_init() }
func file_enums_transactiontype_v1_transaction_type_proto_init() {
	if File_enums_transactiontype_v1_transaction_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enums_transactiontype_v1_transaction_type_proto_rawDesc), len(file_enums_transactiontype_v1_transaction_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enums_transactiontype_v1_transaction_type_proto_goTypes,
		DependencyIndexes: file_enums_transactiontype_v1_transaction_type_proto_depIdxs,
		EnumInfos:         file_enums_transactiontype_v1_transaction_type_proto_enumTypes,
	}.Build()
	File_enums_transactiontype_v1_transaction_type_proto = out.File
	file_enums_transactiontype_v1_transaction_type_proto_goTypes = nil
	file_enums_transactiontype_v1_transaction_type_proto_depIdxs = nil
}
