// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: transaction/service/v1/responses/list_transaction_response.proto

package responses

import (
	requests "github.com/LexBokun/transaction-service/pkg/api/transaction/service/v1/requests"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Возвращает список транзакций с пагинацией(cursor-based)
type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*requests.GetRequest `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`               // Список платежей
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"` // Курсор для следующей страницы (если он есть)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_transaction_service_v1_responses_list_transaction_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_service_v1_responses_list_transaction_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_transaction_service_v1_responses_list_transaction_response_proto_rawDescGZIP(), []int{0}
}

func (x *ListResponse) GetTransactions() []*requests.GetRequest {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ListResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

var File_transaction_service_v1_responses_list_transaction_response_proto protoreflect.FileDescriptor

const file_transaction_service_v1_responses_list_transaction_response_proto_rawDesc = "" +
	"\n" +
	"@transaction/service/v1/responses/list_transaction_response.proto\x12 transaction.service.v1.responses\x1a=transaction/service/v1/requests/get_transaction_request.proto\"\x80\x01\n" +
	"\fListResponse\x12O\n" +
	"\ftransactions\x18\x01 \x03(\v2+.transaction.service.v1.requests.GetRequestR\ftransactions\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursorBRZPgithub.com/LexBokun/transaction-service/pkg/api/transaction/service/v1/responsesb\x06proto3"

var (
	file_transaction_service_v1_responses_list_transaction_response_proto_rawDescOnce sync.Once
	file_transaction_service_v1_responses_list_transaction_response_proto_rawDescData []byte
)

func file_transaction_service_v1_responses_list_transaction_response_proto_rawDescGZIP() []byte {
	file_transaction_service_v1_responses_list_transaction_response_proto_rawDescOnce.Do(func() {
		file_transaction_service_v1_responses_list_transaction_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_service_v1_responses_list_transaction_response_proto_rawDesc), len(file_transaction_service_v1_responses_list_transaction_response_proto_rawDesc)))
	})
	return file_transaction_service_v1_responses_list_transaction_response_proto_rawDescData
}

var file_transaction_service_v1_responses_list_transaction_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_transaction_service_v1_responses_list_transaction_response_proto_goTypes = []any{
	(*ListResponse)(nil),        // 0: transaction.service.v1.responses.ListResponse
	(*requests.GetRequest)(nil), // 1: transaction.service.v1.requests.GetRequest
}
var file_transaction_service_v1_responses_list_transaction_response_proto_depIdxs = []int32{
	1, // 0: transaction.service.v1.responses.ListResponse.transactions:type_name -> transaction.service.v1.requests.GetRequest
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_transaction_service_v1_responses_list_transaction_response_proto_init() }
func file_transaction_service_v1_responses_list_transaction_response_proto_init() {
	if File_transaction_service_v1_responses_list_transaction_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_service_v1_responses_list_transaction_response_proto_rawDesc), len(file_transaction_service_v1_responses_list_transaction_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transaction_service_v1_responses_list_transaction_response_proto_goTypes,
		DependencyIndexes: file_transaction_service_v1_responses_list_transaction_response_proto_depIdxs,
		MessageInfos:      file_transaction_service_v1_responses_list_transaction_response_proto_msgTypes,
	}.Build()
	File_transaction_service_v1_responses_list_transaction_response_proto = out.File
	file_transaction_service_v1_responses_list_transaction_response_proto_goTypes = nil
	file_transaction_service_v1_responses_list_transaction_response_proto_depIdxs = nil
}
