// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: enums/paymentstatus/v1/payment_status.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Статус оплаты(PENDING, SUCCESS, ...)
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_CREATED     Status = 1
	Status_STATUS_PENDING     Status = 2
	Status_STATUS_SUCCESS     Status = 3
	Status_STATUS_FAILED      Status = 4
	Status_STATUS_UNKNOWN     Status = 5
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_CREATED",
		2: "STATUS_PENDING",
		3: "STATUS_SUCCESS",
		4: "STATUS_FAILED",
		5: "STATUS_UNKNOWN",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_CREATED":     1,
		"STATUS_PENDING":     2,
		"STATUS_SUCCESS":     3,
		"STATUS_FAILED":      4,
		"STATUS_UNKNOWN":     5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_enums_paymentstatus_v1_payment_status_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_enums_paymentstatus_v1_payment_status_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_enums_paymentstatus_v1_payment_status_proto_rawDescGZIP(), []int{0}
}

var File_enums_paymentstatus_v1_payment_status_proto protoreflect.FileDescriptor

const file_enums_paymentstatus_v1_payment_status_proto_rawDesc = "" +
	"\n" +
	"+enums/paymentstatus/v1/payment_status.proto\x12\x16enums.paymentstatus.v1*\x83\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_CREATED\x10\x01\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x02\x12\x12\n" +
	"\x0eSTATUS_SUCCESS\x10\x03\x12\x11\n" +
	"\rSTATUS_FAILED\x10\x04\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x05BDZBgithub.com/LexBokun/payment-service/pkg/api/enums/paymentstatus/v1b\x06proto3"

var (
	file_enums_paymentstatus_v1_payment_status_proto_rawDescOnce sync.Once
	file_enums_paymentstatus_v1_payment_status_proto_rawDescData []byte
)

func file_enums_paymentstatus_v1_payment_status_proto_rawDescGZIP() []byte {
	file_enums_paymentstatus_v1_payment_status_proto_rawDescOnce.Do(func() {
		file_enums_paymentstatus_v1_payment_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enums_paymentstatus_v1_payment_status_proto_rawDesc), len(file_enums_paymentstatus_v1_payment_status_proto_rawDesc)))
	})
	return file_enums_paymentstatus_v1_payment_status_proto_rawDescData
}

var file_enums_paymentstatus_v1_payment_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_enums_paymentstatus_v1_payment_status_proto_goTypes = []any{
	(Status)(0), // 0: enums.paymentstatus.v1.Status
}
var file_enums_paymentstatus_v1_payment_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enums_paymentstatus_v1_payment_status_proto_init() }
func file_enums_paymentstatus_v1_payment_status_proto_init() {
	if File_enums_paymentstatus_v1_payment_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enums_paymentstatus_v1_payment_status_proto_rawDesc), len(file_enums_paymentstatus_v1_payment_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enums_paymentstatus_v1_payment_status_proto_goTypes,
		DependencyIndexes: file_enums_paymentstatus_v1_payment_status_proto_depIdxs,
		EnumInfos:         file_enums_paymentstatus_v1_payment_status_proto_enumTypes,
	}.Build()
	File_enums_paymentstatus_v1_payment_status_proto = out.File
	file_enums_paymentstatus_v1_payment_status_proto_goTypes = nil
	file_enums_paymentstatus_v1_payment_status_proto_depIdxs = nil
}
