// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: payment/service/v1/requests/create_payment_request.proto

package requests

import (
	v1 "github.com/LexBokun/payment-service/pkg/api/payment/models/transaction/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Создание транзакции перевода из фиатной валюты в криптовалюту
type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentData   *v1.Transaction        `protobuf:"bytes,1,opt,name=payment_data,json=paymentData,proto3" json:"payment_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_payment_service_v1_requests_create_payment_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_service_v1_requests_create_payment_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_payment_service_v1_requests_create_payment_request_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetPaymentData() *v1.Transaction {
	if x != nil {
		return x.PaymentData
	}
	return nil
}

var File_payment_service_v1_requests_create_payment_request_proto protoreflect.FileDescriptor

const file_payment_service_v1_requests_create_payment_request_proto_rawDesc = "" +
	"\n" +
	"8payment/service/v1/requests/create_payment_request.proto\x12\x1bpayment.service.v1.requests\x1a/payment/models/transaction/v1/transaction.proto\"^\n" +
	"\rCreateRequest\x12M\n" +
	"\fpayment_data\x18\x01 \x01(\v2*.payment.models.transaction.v1.TransactionR\vpaymentDataBIZGgithub.com/LexBokun/payment-service/pkg/api/payment/service/v1/requestsb\x06proto3"

var (
	file_payment_service_v1_requests_create_payment_request_proto_rawDescOnce sync.Once
	file_payment_service_v1_requests_create_payment_request_proto_rawDescData []byte
)

func file_payment_service_v1_requests_create_payment_request_proto_rawDescGZIP() []byte {
	file_payment_service_v1_requests_create_payment_request_proto_rawDescOnce.Do(func() {
		file_payment_service_v1_requests_create_payment_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_service_v1_requests_create_payment_request_proto_rawDesc), len(file_payment_service_v1_requests_create_payment_request_proto_rawDesc)))
	})
	return file_payment_service_v1_requests_create_payment_request_proto_rawDescData
}

var file_payment_service_v1_requests_create_payment_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_payment_service_v1_requests_create_payment_request_proto_goTypes = []any{
	(*CreateRequest)(nil),  // 0: payment.service.v1.requests.CreateRequest
	(*v1.Transaction)(nil), // 1: payment.models.transaction.v1.Transaction
}
var file_payment_service_v1_requests_create_payment_request_proto_depIdxs = []int32{
	1, // 0: payment.service.v1.requests.CreateRequest.payment_data:type_name -> payment.models.transaction.v1.Transaction
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_payment_service_v1_requests_create_payment_request_proto_init() }
func file_payment_service_v1_requests_create_payment_request_proto_init() {
	if File_payment_service_v1_requests_create_payment_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_service_v1_requests_create_payment_request_proto_rawDesc), len(file_payment_service_v1_requests_create_payment_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payment_service_v1_requests_create_payment_request_proto_goTypes,
		DependencyIndexes: file_payment_service_v1_requests_create_payment_request_proto_depIdxs,
		MessageInfos:      file_payment_service_v1_requests_create_payment_request_proto_msgTypes,
	}.Build()
	File_payment_service_v1_requests_create_payment_request_proto = out.File
	file_payment_service_v1_requests_create_payment_request_proto_goTypes = nil
	file_payment_service_v1_requests_create_payment_request_proto_depIdxs = nil
}
