// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: transaction/models/transaction/v1/transaction.proto

package v1

import (
	v1 "github.com/LexBokun/transaction-service/pkg/api/enums/transactionstatus/v1"
	v11 "github.com/LexBokun/transaction-service/pkg/api/enums/transactiontype/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Обменная транзакция, включающая списание и зачисление
type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                 // transaction_id - id транзакции
	Status        v1.Status              `protobuf:"varint,2,opt,name=status,proto3,enum=enums.transactionstatus.v1.Status" json:"status,omitempty"` // Текущий статус транзакции
	Type          v11.Type               `protobuf:"varint,3,opt,name=type,proto3,enum=enums.transactiontype.v1.Type" json:"type,omitempty"`         // Тип транзакции
	From          *Operation             `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`                                             // Операция списания (например, списание с balance)
	To            *Operation             `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`                                                 // Операция зачисления (например, начисление на крипто-кошелек)
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_transaction_models_transaction_v1_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_models_transaction_v1_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_transaction_models_transaction_v1_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Transaction) GetStatus() v1.Status {
	if x != nil {
		return x.Status
	}
	return v1.Status(0)
}

func (x *Transaction) GetType() v11.Type {
	if x != nil {
		return x.Type
	}
	return v11.Type(0)
}

func (x *Transaction) GetFrom() *Operation {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Transaction) GetTo() *Operation {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_transaction_models_transaction_v1_transaction_proto protoreflect.FileDescriptor

const file_transaction_models_transaction_v1_transaction_proto_rawDesc = "" +
	"\n" +
	"3transaction/models/transaction/v1/transaction.proto\x12!transaction.models.transaction.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a1transaction/models/transaction/v1/operation.proto\x1a3enums/transactionstatus/v1/transaction_status.proto\x1a/enums/transactiontype/v1/transaction_type.proto\"\xc8\x02\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12:\n" +
	"\x06status\x18\x02 \x01(\x0e2\".enums.transactionstatus.v1.StatusR\x06status\x122\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1e.enums.transactiontype.v1.TypeR\x04type\x12@\n" +
	"\x04from\x18\x04 \x01(\v2,.transaction.models.transaction.v1.OperationR\x04from\x12<\n" +
	"\x02to\x18\x05 \x01(\v2,.transaction.models.transaction.v1.OperationR\x02to\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtBSZQgithub.com/LexBokun/transaction-service/pkg/api/transaction/models/transaction/v1b\x06proto3"

var (
	file_transaction_models_transaction_v1_transaction_proto_rawDescOnce sync.Once
	file_transaction_models_transaction_v1_transaction_proto_rawDescData []byte
)

func file_transaction_models_transaction_v1_transaction_proto_rawDescGZIP() []byte {
	file_transaction_models_transaction_v1_transaction_proto_rawDescOnce.Do(func() {
		file_transaction_models_transaction_v1_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_models_transaction_v1_transaction_proto_rawDesc), len(file_transaction_models_transaction_v1_transaction_proto_rawDesc)))
	})
	return file_transaction_models_transaction_v1_transaction_proto_rawDescData
}

var file_transaction_models_transaction_v1_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_transaction_models_transaction_v1_transaction_proto_goTypes = []any{
	(*Transaction)(nil),           // 0: transaction.models.transaction.v1.Transaction
	(v1.Status)(0),                // 1: enums.transactionstatus.v1.Status
	(v11.Type)(0),                 // 2: enums.transactiontype.v1.Type
	(*Operation)(nil),             // 3: transaction.models.transaction.v1.Operation
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_transaction_models_transaction_v1_transaction_proto_depIdxs = []int32{
	1, // 0: transaction.models.transaction.v1.Transaction.status:type_name -> enums.transactionstatus.v1.Status
	2, // 1: transaction.models.transaction.v1.Transaction.type:type_name -> enums.transactiontype.v1.Type
	3, // 2: transaction.models.transaction.v1.Transaction.from:type_name -> transaction.models.transaction.v1.Operation
	3, // 3: transaction.models.transaction.v1.Transaction.to:type_name -> transaction.models.transaction.v1.Operation
	4, // 4: transaction.models.transaction.v1.Transaction.created_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_transaction_models_transaction_v1_transaction_proto_init() }
func file_transaction_models_transaction_v1_transaction_proto_init() {
	if File_transaction_models_transaction_v1_transaction_proto != nil {
		return
	}
	file_transaction_models_transaction_v1_operation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_models_transaction_v1_transaction_proto_rawDesc), len(file_transaction_models_transaction_v1_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_transaction_models_transaction_v1_transaction_proto_goTypes,
		DependencyIndexes: file_transaction_models_transaction_v1_transaction_proto_depIdxs,
		MessageInfos:      file_transaction_models_transaction_v1_transaction_proto_msgTypes,
	}.Build()
	File_transaction_models_transaction_v1_transaction_proto = out.File
	file_transaction_models_transaction_v1_transaction_proto_goTypes = nil
	file_transaction_models_transaction_v1_transaction_proto_depIdxs = nil
}
