// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: payment/service/v1/payment_service.proto

package v1

import (
	requests "github.com/LexBokun/payment-service/pkg/api/payment/service/v1/requests"
	responses "github.com/LexBokun/payment-service/pkg/api/payment/service/v1/responses"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_payment_service_v1_payment_service_proto protoreflect.FileDescriptor

const file_payment_service_v1_payment_service_proto_rawDesc = "" +
	"\n" +
	"(payment/service/v1/payment_service.proto\x12\x12payment.service.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a8payment/service/v1/requests/create_payment_request.proto\x1a:payment/service/v1/responses/create_payment_response.proto\x1a5payment/service/v1/requests/get_payment_request.proto\x1a7payment/service/v1/responses/get_payment_response.proto\x1a7payment/service/v1/requests/list_payments_request.proto\x1a9payment/service/v1/responses/list_payments_response.proto2\xea\x06\n" +
	"\x0ePaymentService\x12\x8c\x02\n" +
	"\x06Create\x12*.payment.service.v1.requests.CreateRequest\x1a,.payment.service.v1.responses.CreateResponse\"\xa7\x01\x92A\x86\x01\n" +
	"\apayment\x12,Создание нового платежа\x1aMЭтот метод позволяет создать новый платеж\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/payment/v1/create\x12\xbe\x02\n" +
	"\x03Get\x12'.payment.service.v1.requests.GetRequest\x1a).payment.service.v1.responses.GetResponse\"\xe2\x01\x92A\xc6\x01\n" +
	"\apayment\x12)Получение платежа по ID\x1a\x8f\x01Этот метод возвращает информацию о платеже по его уникальному идентификатору\x82\xd3\xe4\x93\x02\x12\x12\x10/payment/v1/{id}\x12\x87\x02\n" +
	"\x04List\x12(.payment.service.v1.requests.ListRequest\x1a*.payment.service.v1.responses.ListResponse\"\xa8\x01\x92A\x8c\x01\n" +
	"\apayment\x120Получение списка платежей\x1aOЭтот метод возвращает список всех платежей\x82\xd3\xe4\x93\x02\x12\x12\x10/payment/v1/listB@Z>github.com/LexBokun/payment-service/pkg/api/payment/service/v1b\x06proto3"

var file_payment_service_v1_payment_service_proto_goTypes = []any{
	(*requests.CreateRequest)(nil),   // 0: payment.service.v1.requests.CreateRequest
	(*requests.GetRequest)(nil),      // 1: payment.service.v1.requests.GetRequest
	(*requests.ListRequest)(nil),     // 2: payment.service.v1.requests.ListRequest
	(*responses.CreateResponse)(nil), // 3: payment.service.v1.responses.CreateResponse
	(*responses.GetResponse)(nil),    // 4: payment.service.v1.responses.GetResponse
	(*responses.ListResponse)(nil),   // 5: payment.service.v1.responses.ListResponse
}
var file_payment_service_v1_payment_service_proto_depIdxs = []int32{
	0, // 0: payment.service.v1.PaymentService.Create:input_type -> payment.service.v1.requests.CreateRequest
	1, // 1: payment.service.v1.PaymentService.Get:input_type -> payment.service.v1.requests.GetRequest
	2, // 2: payment.service.v1.PaymentService.List:input_type -> payment.service.v1.requests.ListRequest
	3, // 3: payment.service.v1.PaymentService.Create:output_type -> payment.service.v1.responses.CreateResponse
	4, // 4: payment.service.v1.PaymentService.Get:output_type -> payment.service.v1.responses.GetResponse
	5, // 5: payment.service.v1.PaymentService.List:output_type -> payment.service.v1.responses.ListResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_payment_service_v1_payment_service_proto_init() }
func file_payment_service_v1_payment_service_proto_init() {
	if File_payment_service_v1_payment_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_service_v1_payment_service_proto_rawDesc), len(file_payment_service_v1_payment_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_service_v1_payment_service_proto_goTypes,
		DependencyIndexes: file_payment_service_v1_payment_service_proto_depIdxs,
	}.Build()
	File_payment_service_v1_payment_service_proto = out.File
	file_payment_service_v1_payment_service_proto_goTypes = nil
	file_payment_service_v1_payment_service_proto_depIdxs = nil
}
